// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIqgJJx4lYHTEHxrZIT7qQ5puicDEI3PQ',
    appId: '1:755463181889:web:1e4217728a20e8435bd8c0',
    messagingSenderId: '755463181889',
    projectId: 'authtesting-4dc09',
    authDomain: 'authtesting-4dc09.firebaseapp.com',
    storageBucket: 'authtesting-4dc09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr6J4K82Z8mzujhC3jMYIrMv3vEDwU6xA',
    appId: '1:755463181889:android:765690387f15eda05bd8c0',
    messagingSenderId: '755463181889',
    projectId: 'authtesting-4dc09',
    storageBucket: 'authtesting-4dc09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy2HSVjcECDI7_UfZ5tAzke-5MffFMxaQ',
    appId: '1:755463181889:ios:d7195b8fb57b62565bd8c0',
    messagingSenderId: '755463181889',
    projectId: 'authtesting-4dc09',
    storageBucket: 'authtesting-4dc09.appspot.com',
    iosBundleId: 'com.example.xelophone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy2HSVjcECDI7_UfZ5tAzke-5MffFMxaQ',
    appId: '1:755463181889:ios:ea7732f4cc7bbccc5bd8c0',
    messagingSenderId: '755463181889',
    projectId: 'authtesting-4dc09',
    storageBucket: 'authtesting-4dc09.appspot.com',
    iosBundleId: 'com.example.xelophone.RunnerTests',
  );
}
